project_name: micromdm
builds:
  - main: ./cmd/mdmctl
    env: [CGO_ENABLED=0]
    id: "mdmctl"
    binary: mdmctl
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - main: ./cmd/micromdm
    env: [CGO_ENABLED=0]
    id: "micromdm"
    binary: micromdm
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
dockers:
  - image_templates:
#    - "docker.io/myuser/myimage:{{ .Tag }}"
#    - "docker.io/myuser/myimage:latest"
    - "gcr.io/networkpanic/micromdm:{{ .Tag }}"
    - "gcr.io/networkpanic/micromdm:latest"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
