project_name: micromdm
builds:
  - main: ./cmd/mdmctl
    env: [CGO_ENABLED=0]
    id: "mdmctl"
    binary: mdmctl
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

  - main: ./cmd/micromdm
    env: [CGO_ENABLED=0]
    id: "micromdm"
    binary: micromdm
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

universal_binaries:
- replace: true
  name_template: micromdm
  id: "micromdm"

- replace: true
  name_template: mdmctl
  id: "mdmctl"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
